language: go

go:
  - 1.x

before_install:
    - go get github.com/mattn/goveralls
    - go get github.com/vjeantet/ldapserver
    - go get ./...


script:
    - go test -v -covermode=count -coverprofile=coverage.out ./...
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
    - make all test
